# Use official Python image
FROM python:3.10


WORKDIR /app

# Copy project files
COPY . /app


RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8008


CMD ["python3", "manage.py", "runserver", "0.0.0.0:8008"]
