version: '3.8'

services:
  frontend:
    build:
      context: ./mac/frontend_blog/blog-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5005:5005"
    volumes:
      - ./mac/frontend_blog/blog-frontend:/app
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "8008:8008"
    volumes:
      - ./mac:/app
      # - ./mac/db.sqlite3:/app/db.sqlite3 
    networks:
      - app-network
    environment:
      - DEBUG=True

networks:
  app-network:
    driver: bridge
