# Use official Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN npm install

# Expose the frontend port
EXPOSE 5005

# Run the frontend server
CMD ["npm", "run", "dev", "--", "--port", "5005", "--host"]

